name: FIA International
favicon: null
layout_spectrum: 0.4917950672097504
typography_spectrum: 0.1553983895573765
title: FIA International - Importer of Quality Pisco
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff7e00'
    - '#de1118'
    - '#020202'
    - '#7f7f7f'
  brandStrength: 0.916306326398626
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
